35 create tag feature
RaafiKuijper/OCA-app pull request #45
Opened 2024-01-10 09:23 UTC by NolKeereweer

2024-01-10 10:57 UTC, RaafiKuijper requested changes
pretty good overall, but add a test endpoint which adds a basic tag for easier testing and add a tagService so the controller doesnt get cluttered

2024-01-10 10:57 UTC, RaafiKuijper commented on backend/src/main/java/nl/itvitae/ocaapp/tag/Tag.java
> +    private String tagName;
tagName can be renamed to "name", it's already obvious it is a tag name because it is part of the Tag entity/class

2024-01-10 10:57 UTC, RaafiKuijper commented on backend/src/main/java/nl/itvitae/ocaapp/tag/TagController.java
> +        return tagRepository.findAll();
Should be directing to a tagService (which should execute the findall)

2024-01-10 10:57 UTC, RaafiKuijper commented on frontend/src/Tag/ViewTagComponent.tsx
tag folder should be all lowercase

2024-01-10 10:57 UTC, RaafiKuijper commented on frontend/src/Tag/ViewTagComponent.tsx
> +import React from "react";
useless react import

2024-01-10 10:57 UTC, RaafiKuijper commented on frontend/src/Tag/ViewTagComponent.tsx
> +        const res = await axios.get("http://localhost:8080/api/v1/findall");
.../v1/findall doesnt exist, should be v1/tags

2024-01-10 10:57 UTC, RaafiKuijper commented on frontend/src/Tag/ViewTagComponent.tsx
> +        setResult(res.data[0]["tagName"]);
only takes the first tag, change to a for each or something for every tag

2024-01-11 09:02 UTC, BaloeDB approved these changes
Reviewed!

2024-01-11 09:03 UTC, BaloeDB approved these changes
Reviewed!

2024-01-11 09:05 UTC, RaafiKuijper approved these changes

2024-01-11 09:06 UTC, merged